# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ezharness < Formula
  desc "Per-repo evidence gate for git — done means done."
  homepage "https://github.com/thanhhoanace/ezharness"
  version "6.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thanhhoanace/ezharness/releases/download/v6.1.3/ezh_6.1.3_darwin_amd64.tar.gz"
      sha256 "ed8b1863f30891c16c4daaee355a3a650f2d7d3f2a2b0c0735f16582bfd63ece"

      define_method(:install) do
        bin.install "ezh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thanhhoanace/ezharness/releases/download/v6.1.3/ezh_6.1.3_darwin_arm64.tar.gz"
      sha256 "b1d9bcdc0c5cba97e26fd97b6956e94d82a567976ae54914fd13b00b0aac9b68"

      define_method(:install) do
        bin.install "ezh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thanhhoanace/ezharness/releases/download/v6.1.3/ezh_6.1.3_linux_amd64.tar.gz"
      sha256 "63a0b63215b3474feebb8a2b75e3fdd7d7bd3c5ca6cc0008974fcdd9212f4688"
      define_method(:install) do
        bin.install "ezh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thanhhoanace/ezharness/releases/download/v6.1.3/ezh_6.1.3_linux_arm64.tar.gz"
      sha256 "ce19d95042f2551c31b29e0ff7a5152d99a1576d8c5b8f7ae89489dad79f4b24"
      define_method(:install) do
        bin.install "ezh"
      end
    end
  end

  test do
    system "#{bin}/ezh", "version"
  end
end
