# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ezharness < Formula
  desc "Per-repo evidence gate for git — done means done."
  homepage "https://github.com/thanhhoanace/ezharness"
  version "6.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/thanhhoanace/ezharness/releases/download/v6.2.0/ezh_6.2.0_darwin_amd64.tar.gz"
      sha256 "82f87fb71ae8e732ddfe66e938c262ca996bdd0a5db9cc2d4af7076922f29ca2"

      define_method(:install) do
        bin.install "ezh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/thanhhoanace/ezharness/releases/download/v6.2.0/ezh_6.2.0_darwin_arm64.tar.gz"
      sha256 "dc28bf92a94c71195ecb91a51bc5720b362598aab7c65081ed9c88aa77fef3f4"

      define_method(:install) do
        bin.install "ezh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/thanhhoanace/ezharness/releases/download/v6.2.0/ezh_6.2.0_linux_amd64.tar.gz"
      sha256 "f924e19224709049431c59b5df0a53b59ca5d30619a121f63cf5df0fca3f9d60"
      define_method(:install) do
        bin.install "ezh"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/thanhhoanace/ezharness/releases/download/v6.2.0/ezh_6.2.0_linux_arm64.tar.gz"
      sha256 "b2687240cfcdb962594f1af9dd4524011cd4b7b2da833ac0c59348488d3aba95"
      define_method(:install) do
        bin.install "ezh"
      end
    end
  end

  test do
    system "#{bin}/ezh", "version"
  end
end
